surveyops download fail faster

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -79,14 +79,11 @@ jobs:
               env:
                 SURVEYOPS_VERSION: '2.0'
               run: |
-                echo "=== Egress IP ==="
+                echo "=== Determine Egress IP ==="
                 curl -s https://ifconfig.me || curl -s https://ipinfo.io/ip || curl -s https://api.ipify.org
                 echo
                 echo "=== Download attempt (verbose) ==="
-                wget -v --timeout=10 --tries=1 https://data.desi.lbl.gov/public/epo/example_files/surveyops_${SURVEYOPS_VERSION}_ops.tar.gz
-                echo
-                echo "=== Unpacking ==="
-                tar xzf surveyops_${SURVEYOPS_VERSION}_ops.tar.gz
+                (wget -v --timeout=10 --tries=1 https://data.desi.lbl.gov/public/epo/example_files/surveyops_${SURVEYOPS_VERSION}_ops.tar.gz && tar xzf surveyops_${SURVEYOPS_VERSION}_ops.tar.gz) || echo "Download of surveyops failed, moving on"
             - name: Run the test
               run: DESI_SURVEYOPS=$(pwd) pytest
 
